name: RemoteController
main: hide92795.bukkit.plugin.remotecontroller.RemoteController
version: 1.6.2_5
description: RemoteController
author: hide92795
depend: [hide92795CoreLib]
softdepend: [dynmap]

commands:
  remotecontroller:
    permission: remotecontroller
    aliases: [rc]
  remotecontroller-user:
    permission: remotecontroller.user
    aliases: [rcu]
  remotecontroller-reload:
    permission: remotecontroller.reload
    aliases: [rcr]